server:
  port: 9500

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: client
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/**
        - id: load
          uri: lb://LOAD-SERVICE
          predicates:
            - Path=/**